/*
 *	Comment or uncomment to enable sensors/modules for the warp board
 */

#define WARP_BUILD_ENABLE_DEVADXL362
#define WARP_BUILD_ENABLE_DEVMMA8451Q
#define WARP_BUILD_ENABLE_DEVLPS25H
#define WARP_BUILD_ENABLE_DEVHDC1000
#define WARP_BUILD_ENABLE_DEVMAG3110
#define WARP_BUILD_ENABLE_DEVSI7021
#define WARP_BUILD_ENABLE_DEVL3GD20H
#define WARP_BUILD_ENABLE_DEVBME680
#define WARP_BUILD_ENABLE_DEVTCS34725
#define WARP_BUILD_ENABLE_DEVSI4705
#define WARP_BUILD_ENABLE_DEVCCS811
#define WARP_BUILD_ENABLE_DEVAMG8834
#define WARP_BUILD_ENABLE_DEVPAN1326
#define WARP_BUILD_ENABLE_DEVAS7262
#define WARP_BUILD_ENABLE_DEVAS7263
#define WARP_BUILD_ENABLE_DEVRV8803C7

